repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --args=--lockfile=false         # Disable lockfile check, should be used only for Terraform modules!
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--skip-check CKV_AWS_158 # AWS CloudWatch Log groups encrypted using default encryption key instead of KMS CMK
        - --args=--skip-check CKV_AWS_338 # AWS CloudWatch log groups retention set to less than 365 days

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
